export const BOOK_REQUEST  = 'BOOK_REQUEST'
export const BOOK_SUCCESS = 'BOOK_SUCCESS'
export const BOOK_FAILURE = 'BOOK_FAILURE'

export const BOOK_DETAIL_REQUEST  = 'BOOK_DETAIL_REQUEST'
export const BOOK_DETAIL_SUCCESS = 'BOOK_DETAIL_SUCCESS'
export const BOOK_DETAIL_FAILURE = 'BOOK_DETAIL_FAILURE'

